services:
  db:
    image: postgres:15
    container_name: oursys_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oursysdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    volumes:
      - ./server/uploads:/app/uploads
    container_name: oursys_server
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma db push && node dist/main.js"
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://oursys-dev.site
    container_name: oursys_frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
      - frontend

volumes:
  db_data:
